from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from io import BytesIO
from datetime import datetime

def generate_pdf_report(scan_data):
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter)
    elements = []
    
    styles = getSampleStyleSheet()
    title_style = styles['Title']
    heading_style = styles['Heading2']
    normal_style = styles['Normal']
    
    # Custom Style
    code_style = ParagraphStyle(
        'Code',
        parent=styles['BodyText'],
        fontName='Courier',
        fontSize=9,
        leading=12,
        backColor=colors.lightgrey,
    )

    # Title
    elements.append(Paragraph("VulnX Security Scan Report", title_style))
    elements.append(Spacer(1, 12))
    
    # Meta Info
    elements.append(Paragraph(f"<b>Target:</b> {scan_data.get('target', 'Unknown')}", normal_style))
    elements.append(Paragraph(f"<b>IP Address:</b> {scan_data.get('ip', 'Unknown')}", normal_style))
    elements.append(Paragraph(f"<b>Scan Date:</b> {scan_data.get('timestamp', datetime.now().strftime('%Y-%m-%d %H:%M:%S'))}", normal_style))
    elements.append(Paragraph(f"<b>Scan Type:</b> {'Deep Scan (1-1024)' if scan_data.get('deep_scan') else 'Quick Scan (Top Ports)'}", normal_style))
    elements.append(Spacer(1, 24))
    
    # Vulnerability Summary
    ports = scan_data.get('results', []) # Adapt to whatever key holds the ports list
    if not ports and 'ports_found' in scan_data:
         # If persisted history structure differs from runtime
         pass

    elements.append(Paragraph(f"Open Ports Detected: {len(ports)}", heading_style))
    elements.append(Spacer(1, 12))

    if ports:
        # Table Header
        data = [['Port', 'Service', 'Banner', 'Severity', 'Threat / Assessment']]
        
        # Table Data
        for p in ports:
            # p structure: [port, service, banner, severity, threat]
            port_num = str(p[0])
            service = p[1]
            banner = p[2][:30] + "..." if len(p[2]) > 30 else p[2]
            severity = p[3]
            threat = p[4]
            
            data.append([port_num, service, banner, severity, threat])
            
        # Table Style
        table = Table(data, colWidths=[40, 60, 120, 60, 250])
        table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#0a0c10')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 10),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, 1), (-1, -1), colors.white),
            ('GRID', (0, 0), (-1, -1), 1, colors.black),
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            ('WORDWRAP', (0, 0), (-1, -1), True),
        ]))
        
        elements.append(table)
    else:
        elements.append(Paragraph("No open ports were detected during this scan.", normal_style))

    elements.append(Spacer(1, 24))
    
    # Footer
    elements.append(Spacer(1, 48))
    elements.append(Paragraph("Generated by VulnX Professional Edition", 
        ParagraphStyle('Footer', parent=normal_style, alignment=1, textColor=colors.grey)))

    doc.build(elements)
    buffer.seek(0)
    return buffer
